# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Attribute-Overload-Match
version:      0.01
version_from: Match.pm
installdirs:  site
requires:
    Attribute::Handlers:           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
